### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by daemonspudguy** [ungstein/OG-Steam-Library#1]
I use Linux and would like to know if this library skin can be used somehow?

**Comment by ungstein** [comment]
All the information regarding this is in the Readme:

https://github.com/ungstein/OG-Steam#installing

This skin can definitely be used with the Steam client for Linux but there may be some minor glitches. If you spot any, please let me know.

**Comment by daemonspudguy** [comment]
OK, but the library is still blue, not the green one shown here

**Comment by ungstein** [comment]
The green Library preview is for [OG-Steam-Library](https://github.com/ungstein/OG-Steam-Library), which uses [SteamFriendsPatcher](https://github.com/PhantomGamers/SteamFriendsPatcher). Unfortunately, SteamFriendsPatcher isn't a native Linux application but may work with steam when both are run under WINE.
