### ISSUE TITLE
Custom Artwork Button

### ISSUE THREAD

**Issue by GRIMMboi** [ungstein/OG-Steam-Library#1]
The background for the done button doesn't stretch over the whole text.

![image](https://user-images.githubusercontent.com/29306311/128902975-536c2620-986f-490f-86e0-dd8ed55ae1e5.png)

**Comment by ungstein** [comment]
Thank you for pointing this out. I have taken a look at this before and couldn't work out how to make the button bigger. It's on the list.

**Comment by ungstein** [comment]
This has been fixed in the beta branch.
