### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by Velken** [ungstein/OG-Steam-Library#10]
Up until yesterday it war working fine, now my library is an amalgamation of both styles

![image](https://user-images.githubusercontent.com/8467292/160745163-cec0c216-12e8-46ad-b583-9c4cf81bcaea.png)

![image](https://user-images.githubusercontent.com/8467292/160745198-fab06d8e-1ce0-4e17-8000-4947529a3899.png)

![image](https://user-images.githubusercontent.com/8467292/160745256-1bb339eb-3a54-417c-b80f-e5193c6f8472.png)

**Comment by ungstein** [comment]
This is due to a Steam update that changed filenames. Change "Library CSS" to 7.css (currently 0.css). Three users have confirmed this works so far.

**Comment by Velken** [comment]
this is with 7.css

![image](https://user-images.githubusercontent.com/8467292/161007408-cefd308e-6bed-4803-a609-7d61462b3c40.png)

![image](https://user-images.githubusercontent.com/8467292/161007525-8c3f6104-fe0c-4cb6-ba45-e35b83ccf972.png)

![image](https://user-images.githubusercontent.com/8467292/161007547-10da2cb5-c00e-4cc4-a8a7-2b246b0826f4.png)

**Comment by ungstein** [comment]
Okay, looks like you may have better luck following the steps mentioned <a href="https://steamcommunity.com/groups/og-skin/discussions/1/3187992943275121931/#c3274687384240286949">here.</a>
