### ISSUE TITLE
can't add new steam library

### ISSUE THREAD

**Issue by Velken** [ungstein/OG-Steam-Library#11]
![image](https://user-images.githubusercontent.com/8467292/164118054-6dc4513a-0e16-4fa3-aa11-bf53c0719b3d.png)

button is grayed out, clicking it doesn't work

**Comment by isopropyl-alco** [comment]
I am experiencing this issue as well.

**Comment by ungstein** [comment]
Thanks, I'll look into it.

**Comment by ungstein** [comment]
Steam update caused the title bar to overlap the carousel. All fixed now.
