### ISSUE TITLE
Color doesn't apply to What's New

### ISSUE THREAD

**Issue by Plut0nio** [ungstein/OG-Steam-Library#2]
![steam_qZ9VaC6KUu](https://user-images.githubusercontent.com/24761328/119763505-a8603980-be7d-11eb-8065-325293bdb7f6.png)
![steamwebhelper_ATB7q4GYq9](https://user-images.githubusercontent.com/24761328/119763634-e78e8a80-be7d-11eb-80b2-bf9e778b026f.png)

As you can see, the olive color doesn't apply to the What's New section of my library nor does it apply to its settings window. As far as I can tell, this is the only part of my library that the color doesn't apply to.

**Comment by ungstein** [comment]
Hi Plut0nio, thanks for trying OGS and OGSL. Currently, I have yet to edit the colour scheme for What's New. I plan on doing so soon. I will post here when it is done.

**Comment by ungstein** [comment]
This has been fixed in the latest update.
