### ISSUE TITLE
Is the new download page web-based like the library?

### ISSUE THREAD

**Issue by isopropyl-alco** [ungstein/OG-Steam-Library#3]
Hello, just a question?

Is the new downloads paged web-based like friends and library? I have a feeling it could be but what about the new storage manager page? I feel that may be integrated into the client.

Thanks.

**Comment by ungstein** [comment]
All updates to the UI since the new Friends/Chat have been web-based. Valve is gradually converting Steam to a web app.

**Comment by isopropyl-alco** [comment]
Yes, unfortunately it’s the sad reality, and it’s  unnecessary too. It’s only a matter of time before the whole Steam client becomes a massive web browser and none of the skins we’ve known for years will work anymore. They don't even need to do this, is their intention to put the whole Steam client online? But the reason they are continuing to make it web based is probably because they can design a better UI in their eyes with CSS.

At least Valve is doing it well and it’s not extremely slow like some desktop web apps like Microsoft Teams.

**Comment by ungstein** [comment]
Don't get me started on Teams.
