### ISSUE TITLE
Steam Friends list remains as default theme

### ISSUE THREAD

**Issue by ayashi76** [ungstein/OG-Steam-Library#6]
![image](https://user-images.githubusercontent.com/94764049/142741011-adfefd93-b0ce-4317-9ea0-3f8672f650d3.png)
as you can see in image the friends list remains in default theme? i dont know if this is a error on my part or not

**Comment by ayashi76** [comment]
> I am happy to receive pull requests.

alrighty! i will look into modifying the theme to add it since friends and friend chat is used alot by many people so fixing it would be nice

**Comment by ungstein** [comment]
> 

Agreed. I look forward to what you come up with :)

**Comment by ungstein** [comment]
> > I am happy to receive pull requests.
> 
> alrighty! i will look into modifying the theme to add it since friends and friend chat is used alot by many people so fixing it would be nice

Agreed. I look forward to what you come up with :)

**Comment by ungstein** [comment]
One thing I should mention. I'm currently working on the beta branch, which contains significant changes to the way things are laid out. Please base your theme on that version.

**Comment by leonill007** [comment]
There already is a green steam friends skin: https://github.com/finland/OG-Steam-Friends
