### ISSUE TITLE
Live version for beta

### ISSUE THREAD

**Issue by ghost** [ungstein/OG-Steam-Library#7]
Hello there! I was wondering if you could do a live version of OG-Steam-Library for the beta branch. I tried modifying the import url, but that didn't really help heh

**Comment by ungstein** [comment]
Thanks for the suggestion. I plan to do this soon.

**Comment by ungstein** [comment]
[Here you go.](https://github.com/ungstein/ungstein.github.io/raw/main/og-steam-library-beta/og-steam-library-beta-live.zip)

**Comment by ghost** [comment]
Appreciated!
